name: Author update

on:
  pull_request:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Pull Request Comment Trigger
        uses: Khan/pull-request-comment-trigger@1.0.0
        with:
          trigger: "#update"
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run update
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      - run: git add .
      - run: git config --local user.email "???"
      - run: git config --local user.name "anyunderhood"
      - run: git commit -m 'Update of authors happened'
#       - run: git switch -c ${{ github.head_ref }}
      - run: git push # origin
#       - name: GitHub Push
#         uses: ad-m/github-push-action@v0.5.0
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: ${{ github.head_ref }}
#       - name: Push changes
#         uses: actions-go/push@v1
#         with:
          # Override the existing remote branch if it already exist
#           force: # optional
          # The email that will appear in commits when changes needs to be committed
#           author-email: # optional, default is actions-go@users.noreply.github.com
          # The name that will appear in commits when changes needs to be committed
#           author-name: # optional, default is ActionsGo Bot
          # Instructs to create a commit with changed files
#           create-commit: # optional, default is true
          # A coma separated list of files to add to commit in addition to already staged ones. If not provided, all tracked files are committed.
#           commit-files: # optional
          # The commit message used when changes needs to be committed
#           commit-message: 
          # The name of the local reference to push.
#           ref: ${{ github.head_ref }} # optional, default is ${{ github.ref }}
          # The name of the remote on which to push the changes. Defaults to the tracked remote
#           remote: # optional, default is origin
          # The name of the remote reference to pushto. Defaults to the tracked remote branch.
#           remote-ref: # optional, default is ${{ github.ref }}
          # Fail the action in case there is nothing to do.
#           fail-if-empty: # optional
          # Auth token used to fetch the repository. The token is stored in the local git config, which enables your scripts to run authenticated git commands. The post-job step removes the token from the git config. [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
#           token: # optional, default is ${{ github.token }}
