name: Build & deploy to anyunderhood/anyunderhood.github.io

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - name: GitHub Push
      uses: ad-m/github-push-action@ad-m-patch-1
      with:
        # Token for the repo. Can be passed in using  $\{{ secrets.GITHUB_TOKEN }}
        github_token: $\{{ secrets.CUSTOM_GITHUB_TOKEN }}
        # Repositoryname to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
        repository: anyunderhood/anyunderhood.github.io
        force: true
        # Directory to change to before pushing.
        directory: dist
    
